name: censor_it
description: A Dart library for censoring text based on predefined patterns and customizable characters.
version: 1.2.4
repository: https://github.com/pavluke/censor_it
homepage: https://github.com/pavluke/censor_it
issue_tracker: https://github.com/pavluke/censor_it/issues

environment:
  sdk: ^3.3.4

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.12

topics:
  - censorship
  - profanity-filter
  - text-processing
  - multilingual
  - dart-library

screenshots:
  - description: "CensorIt Logo"
    path: images/logo.png
  - description: "CensorIt Banner"
    path: images/banner.png
