name: censor_it
description: A Dart library for censoring text based on predefined patterns and customizable characters.
version: 2.0.0
repository: https://github.com/pavluke/censor_it
homepage: https://github.com/pavluke/censor_it
issue_tracker: https://github.com/pavluke/censor_it/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.28.0

topics:
  - censorship
  - profanity-filter
  - text-processing
  - multilingual
  - dart-library

screenshots:
  - description: "CensorIt Logo"
    path: images/logo.png
  - description: "CensorIt Banner"
    path: images/banner.png
